# Generated by Django 4.2.11 on 2024-06-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_upload_images_user_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_images',
            name='user_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
